### PR TITLE
[JXR-153] use locales for string comparison

### PR DESCRIPTION
**Pull request by elharo**
@slachiewicz

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
Please change commit message from "use lcoales for string comparison" to 
"[JXR-153] use locales for string comparison" - PR title will not propagate to git

**Comment by slachiewicz** [comment]
If ypu plan to as for review - You can use Github Reviewers - top right, instead of putting someone's name on the first comment.

**Review by elharo — COMMENTED** [review]
done

**Comment by jira-importer** [comment]
Resolve #225

**Pull request merged**
