### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by michael-o** [comment]
I think this needs to be split up on several issues. @hboutemy WDYT=

**Comment by hboutemy** [comment]
there is no issue at all, then splitting won't change anything :)
when upgrading parent pom, adding project.build.outputTimestamp is good practice

**Comment by michael-o** [comment]
I was referring to JIRA issues for the release notes.

**Comment by michael-o** [comment]
I most cases yes. I think our rule of thumb is if it does not affect the code, e.g, typos, or small text changes, it does not need a JIRA issue. But dependency updates affect code at compile or runtime.

**Pull request closed without merging**
